[package]
name = "railwayapp"
version = "3.4.0"
edition = "2021"
license = "MIT"
authors = ["Railway <contact@railway.app>"]
description = "Interact with Railway via CLI"
readme = "README.md"
homepage = "https://github.com/railwayapp/cli"
repository = "https://github.com/railwayapp/cli"
rust-version = "1.67.1"
default-run = "railway"
include = ["src/**/*", "LICENSE", "README.md"]

[[bin]]
name = "railway"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.6", features = ["derive", "suggestions"] }
colored = "2.0.4"
dirs = "5.0.1"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
reqwest = { version = "0.11.20", default-features = false, features = [
  "rustls-tls",
] }
chrono = { version = "0.4.31", features = ["serde"], default-features = false }
graphql_client = { version = "0.13.0", features = ["reqwest-rustls"] }
paste = "1.0.14"
tokio = { version = "1.32.0", features = ["full"] }
clap_complete = "4.4.3"
open = "5.0.0"
inquire = "0.6.2"
hyper = { version = "0.14.27", features = ["server", "http1"] }
base64 = "0.21.4"
http-body-util = "0.1.0-rc.2"
rand = "0.8.5"
hostname = "0.3.1"
indicatif = "0.17.7"
indoc = "2.0.4"
console = "0.15.7"
box_drawing = "0.1.2"
textwrap = "0.16.0"
gzp = { version = "0.11.3", default-features = false, features = [
  "deflate_rust",
] }
tar = "0.4.40"
synchronized-writer = "1.1.11"
ignore = "0.4.20"
num_cpus = "1.16.0"
url = "2.4.1"
futures = { version = "0.3.28", default-features = false, features = [
  "compat",
  "io-compat",
] }
uuid = { version = "1.4.1", features = ["serde", "v4"] }
httparse = "1.8.0"
names = { version = "0.14.0", default-features = false }
graphql-ws-client = { version = "0.5.0", features = ["client-graphql-client"] }
async-tungstenite = { version = "0.23.0", features = [
  "tokio-runtime",
  "tokio-rustls-native-certs",
] }
is-terminal = "0.4.9"
serde_with = "3.3.0"
ctrlc = "3.4.1"
which = "4.4.2"
thiserror = "1.0.49"
winapi = {version="0.3.9", features = ["minwindef", "tlhelp32", "processthreadsapi", "handleapi", "winerror"]}
