on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: CI

jobs:
  rust:
    name: Check
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
        - uses: Swatinem/rust-cache@v2
        - run: cargo fmt --all -- --check
        - run: cargo check --workspace --locked
        - run: cargo clippy --all-targets --all-features

  test-plan:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
        - uses: Swatinem/rust-cache@v2
        - run: cargo test
