name: Create Release PR

on:
  pull_request:
    types: [ closed ]

jobs:
  create-pr-release:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-ecosystem/action-get-merged-pull-request@v1
        id: get-merged-pull-request
        with:
          github_token: ${{ secrets.GH_PAT }}

      - uses: actions-ecosystem/action-release-label@v1
        id: release-label
        if: ${{ steps.get-merged-pull-request.outputs.title != null }}
        with:
          github_token: ${{ secrets.GH_PAT }}
          labels: ${{ steps.get-merged-pull-request.outputs.labels }}

      - name: Install cargo-release
        uses: taiki-e/install-action@v1
        with:
          tool: cargo-release

      - uses: cargo-bins/release-pr@v2
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          github-token: ${{ secrets.GH_PAT }}
          version: ${{ steps.release-label.outputs.level }}
          pr-label: release/pending
          pr-title: "Release v<%= version.actual %>"
          pr-release-notes: true
          pr-merge-strategy: squash
