name: Publish

on:
  workflow_run:
    workflows: [ "Release" ]
    types:
      - completed

jobs:
  publish_npm:
    # Publish to NPM only if the release workflow succeeded
    if: github.event.workflow_run.conclusion == 'success'
    name: Publish NPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set version
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Setup Git user
        run: |
          git config --global user.name "Github Bot"
          git config --global user.email "github-bot@railway.app"

      - name: Create .npmrc file
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: NPM publish
        run: npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
