name: Release
on: pull_request
env:
  MACOSX_DEPLOYMENT_TARGET: 10.7

jobs:
  build-release:
    name: Build Release Assets
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked --target x86_64-unknown-linux-musl
          use-cross: true

      - name: Upload docker artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-binary-artifact-x86_64-unknown-linux-musl
          path: target/x86_64-unknown-linux-musl/release

      - name: Store docker artifact version
        run: echo "3.13.1" >> cli-version.txt

      - name: Upload docker artifact version
        uses: actions/upload-artifact@v4
        with:
          name: docker-tag-artifact
          path: cli-version.txt
