name: Tag

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: chainguard-dev/actions/setup-gitsign@main

      - uses: actions-ecosystem/action-get-merged-pull-request@v1
        id: get-merged-pull-request
        with:
          github_token: ${{ secrets.GH_PAT }}

      - uses: actions-ecosystem/action-release-label@v1
        id: release-label
        if: ${{ steps.get-merged-pull-request.outputs.title != null }}
        with:
          github_token: ${{ secrets.GH_PAT }}
          labels: ${{ steps.get-merged-pull-request.outputs.labels }}

      - name: Install cargo-release
        uses: taiki-e/install-action@v1
        with:
          tool: cargo-release

      - uses: cargo-bins/release-pr@v2
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          level: ${{ steps.release-label.outputs.level }}
          pr-label: release
